#!/bin/sh

echo "please enter scan path:"

read mdir

if [ -z $mdir ]
then
    echo "make sure the path is correct!"
    exit
fi

for file in $(find $mdir -type l)
do
    if [ ! -e $file ]
    then
        echo "rm $file"
        rm -f $file
    fi
done
